### ISSUE TITLE
Internal Server error on Nodes and reports

### ISSUE THREAD

**Issue by grayzu** [claudiospizzi/DSCPullServerWeb#6]
Hey Claudio,

I am trying to get this up and running but am running on Windows Server 2016 but am hitting the a pretty generic error. Any idea what might cause this?

Few details about my installation:
- Installing in a Workgroup (no domain)
- Can access website and see your UI
- is installed with and using the Esent DB.

Love what you have done here so any help would be greatly appreciated.

MarkG

**Comment by claudiospizzi** [comment]
Hi Mark

Where do you hit the generic error, on which url?

Can you check the application event log: There should be an error log with the source "DSC Pull Server Web" and an id around 10000.

Does your EsentDB exist an does it have nodes in it?

Bests

**Comment by grayzu** [comment]
It happened on the /Web/Nodes and the /Web/Reports URLs. Seems to work after I viewed the contents of the DB with a tool. Weird but probably not an issue with your code.

Thanks,
MarkG
